### ISSUE TITLE
Anchor private feeds

### ISSUE THREAD

**Issue by jamescridland** [Podcastindex-org/private-feed-blocklist#6]
The following are used in paid Spotify subscriptions. I’m not that good with regex, so am lazily leaving it for you, @daveajones (or someone else) to do a PR.

```
https://anchor.fm/s/%/podcast/auth/%
https://anchor.fm/s/%/podcast/private?token=%
```

**Comment by daveajones** [comment]
I’ll get these included and tweaked.
